name:                Game2048
version:             0.1.0.0
github:              "pe200012/Game2048"
license:             BSD3
author:              "pe200012"
maintainer:          "1326263755@qq.com"
copyright:           "2021 pe200012"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Game2048#readme>

dependencies:
- base >= 4.7 && < 5
- array
- random
- mtl
- monad-loops

library:
  source-dirs: src

executables:
  Game2048-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Game2048

tests:
  Game2048-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Game2048
